### PR TITLE
Updating and Optimisation of Gradient Boosting Classifier algorithm

### PR DESCRIPTION
**Pull request by debjitpal5040**
Linked Issue: #13 

## Changes
- Updated Gradient Boosting Classifier and optimised it
Check the new notebook from here : https://colab.research.google.com/drive/1f5gV0eQcuVaMhR2qT9-oDMW-UecCO6zf?usp=sharing

### CODE REVIEW

**Comment by agnisain123** [comment]
You need to add more parameters to the gradient boosting classifier. Also, you have to update the .pkl file too. That file will be used for the flask app. Try some ensembling approach to improve its accuracy.

**Comment by debjitpal5040** [comment]
> You need to add more parameters to the gradient boosting classifier. Also, you have to update the .pkl file too. That file will be used for the flask app. Try some ensembling approach to improve its accuracy.

Okay I have added some more parameters to the gradient boosting classifier to improve its accuracy and it has been improved. But can you please tell me how do I update the .pkl file? and why we are also creating "xgb.pkl" file while it is not in use? I can't comprehend your point about updating "gbc.pkl" file as ...

filename='gbc.pkl'
with open(filename,'wb') as f:
    pickle.dump(gbc,f)

Is not this code does that which is executed after the gradient boosting classifier??

**Comment by agnisain123** [comment]
<p>Each time you make changes in the GradientBoostingClassifier cell, a new gbc.pkl file will be created. You have to replace the old file with the new one to reflect the changes in the flask app.</p> The xgb.pkl was used for testing purposes. You can remove it as we are not using it right now.

**Comment by debjitpal5040** [comment]
> Each time you make changes in the GradientBoostingClassifier cell, a new gbc.pkl file will be created. You have to replace the old file with the new one to reflect the changes in the flask app.
> 
> The xgb.pkl was used for testing purposes. You can remove it as we are not using it right now.

Okay okay got it, thanks

**Comment by agnisain123** [comment]
Do keep asking your doubts, I'll do my best to solve them. Keep up the good work!

**Comment by debjitpal5040** [comment]
Okay as you told I have changed and updated .pkl file. Now review this please.

**Comment by debjitpal5040** [comment]
@agnisain123 hey have you checked it out ? It's been a long time since I have made this PR. Is everything okay?

**Comment by agnisain123** [comment]
Looks good to me. Well done!

**Pull request merged**
